# Generated by Django 5.0.6 on 2024-09-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
