# Generated by Django 5.0.6 on 2024-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
