# Generated by Django 5.1.1 on 2024-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Default.jpg', upload_to='profile_pics'),
        ),
    ]
