# Generated by Django 5.1.1 on 2024-12-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovers', '0007_alter_post_options_alter_post_title_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='Course',
        ),
    ]
